export interface PeriodicElement {
	type: string,
	username: string,
	name: string,
	owner: string,
	homepage: string,
	description: string,
	language: string,
	watchers: number,
	followers: number,
	forks: number,
	size: number,
	open_issues: number,
	score: number,
	has_downloads: boolean,
	has_issues: boolean,
	has_projects: boolean,
	has_wiki: boolean,
	fork: boolean,
	private: boolean,
	url: string,
	created: string,
	created_at: string,
	pushed_at: string,
	pushed: string
}